import express from 'express';
import { appointments, cancelAppointmentForDoctorAndUser, latestAppointmentsForDoctors, totalAppointments, totalDoctors, totalPatients } from '../controllers/appointment.controller.js';
import { verifyToken } from '../middleware/verifyToken.js';
const route = express.Router();
route.get('/admin-total-doctor', verifyToken('admin'), totalDoctors);
route.get('/admin-total-appointment', verifyToken('admin'), totalAppointments);
route.get('/admin-total-patient', verifyToken('admin'), totalPatients);
route.get('/admin-latest-appointment', verifyToken('admin'), latestAppointmentsForDoctors);
route.get('/admin-appointment', verifyToken('admin'), appointments);
route.post('/admin-cancel-appointment', verifyToken('admin'), cancelAppointmentForDoctorAndUser);
export default route;